In [7]:
import pandas as pd
from pathlib import Path

In [8]:
base = Path("/Users/linhle/LinhLe/Apprentisage/EFREI/S1_2025/Data_visualization/Mano_Part/Project_streamlit")
csv_path = base / "data" / "data_cleaned.csv"

In [9]:
df = pd.read_csv(csv_path, sep=',', engine='python')
df

,region,departement,mois,allocataires_total,ouvertures_droit,ouvertures_initiales,reprises,fins_droit,allocation_jour,duree_moy,allocataires_indemnises,allocataires_aref,allocataires_asp,indemnisation_moy_net,indemnisation_moy_trav,indemnisation_moy_non_trav,part_trav_mois,part_trav_mois_indemnise,depense_mensuelle,code_dep
0,Auvergne-Rhône-Alpes,01 - Ain,2020-01-01,36281.0,2134.0,1573.0,1261.0,627.00,45.4,552.0,27238.0,1260.0,465.0,1057.645441,739.179632,1215.104722,0.456548,0.248394,3.265899e+07,01
1,Auvergne-Rhône-Alpes,01 - Ain,2020-02-01,35719.0,1694.0,1155.0,977.0,628.00,45.7,556.0,25842.0,1163.0,474.0,1016.897078,711.340126,1160.940383,0.469918,0.231753,2.966521e+07,01
2,Auvergne-Rhône-Alpes,01 - Ain,2020-03-01,37751.0,1963.0,1881.0,1705.0,1033.75,44.6,552.0,28609.0,1152.0,452.0,1055.638490,737.952710,1222.726465,0.445684,0.261185,3.340788e+07,01
3,Auvergne-Rhône-Alpes,01 - Ain,2020-04-01,39440.0,1602.0,1525.0,1170.0,1439.50,46.4,576.0,32469.0,1124.0,443.0,1081.241436,811.678102,1159.762211,0.323631,0.185674,3.831568e+07,01
4,Auvergne-Rhône-Alpes,01 - Ain,2020-05-01,39798.0,1085.0,998.0,733.0,1845.25,48.7,588.0,32855.0,1141.0,458.0,1118.422187,803.022535,1230.658590,0.363586,0.216669,4.018381e+07,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7339,Provence-Alpes-Côte d'Azur,Total,2024-11-01,334986.0,20067.0,14640.0,13010.0,6834.00,40.2,460.0,246976.0,11049.0,5597.0,1028.960108,908.768412,1086.695385,0.459613,0.239198,2.818785e+08,Total
7340,Provence-Alpes-Côte d'Azur,Total,2024-12-01,334458.0,17797.0,11533.0,9548.0,7284.00,41.1,469.0,251222.0,9838.0,5704.0,1069.247804,917.961280,1142.164298,0.462079,0.244249,2.982640e+08,Total
7341,Provence-Alpes-Côte d'Azur,Total,2025-01-01,335062.0,19151.0,13957.0,10344.0,7088.00,41.9,474.0,252347.0,10757.0,5642.0,1070.020922,929.050634,1135.088206,0.450093,0.237804,3.009900e+08,Total
7342,Provence-Alpes-Côte d'Azur,Total,2025-02-01,330274.0,14173.0,9787.0,7288.0,6528.00,41.5,472.0,242521.0,11039.0,5493.0,984.470527,856.126423,1041.835817,0.459325,0.226797,2.658311e+08,Total
7343,Provence-Alpes-Côte d'Azur,Total,2025-03-01,325311.0,14984.0,10411.0,8092.0,6981.00,42.0,477.0,237826.0,11268.0,5318.0,1072.869623,917.618733,1151.874261,0.483113,0.246533,2.847394e+08,Total

In [10]:
df.shape

(7344, 20)

In [16]:
numerical_col_names = df.select_dtypes(include=['number']).columns
numerical_col_names

Index(['allocataires_total', 'ouvertures_droit', 'ouvertures_initiales',
       'reprises', 'fins_droit', 'allocation_jour', 'duree_moy',
       'allocataires_indemnises', 'allocataires_aref', 'allocataires_asp',
       'indemnisation_moy_net', 'indemnisation_moy_trav',
       'indemnisation_moy_non_trav', 'part_trav_mois',
       'part_trav_mois_indemnise', 'depense_mensuelle'],
      dtype='object')

In [18]:
df_num = df.select_dtypes(include=['int64', 'float64'])
df_num

,allocataires_total,ouvertures_droit,ouvertures_initiales,reprises,fins_droit,allocation_jour,duree_moy,allocataires_indemnises,allocataires_aref,allocataires_asp,indemnisation_moy_net,indemnisation_moy_trav,indemnisation_moy_non_trav,part_trav_mois,part_trav_mois_indemnise,depense_mensuelle
0,36281.0,2134.0,1573.0,1261.0,627.00,45.4,552.0,27238.0,1260.0,465.0,1057.645441,739.179632,1215.104722,0.456548,0.248394,3.265899e+07
1,35719.0,1694.0,1155.0,977.0,628.00,45.7,556.0,25842.0,1163.0,474.0,1016.897078,711.340126,1160.940383,0.469918,0.231753,2.966521e+07
2,37751.0,1963.0,1881.0,1705.0,1033.75,44.6,552.0,28609.0,1152.0,452.0,1055.638490,737.952710,1222.726465,0.445684,0.261185,3.340788e+07
3,39440.0,1602.0,1525.0,1170.0,1439.50,46.4,576.0,32469.0,1124.0,443.0,1081.241436,811.678102,1159.762211,0.323631,0.185674,3.831568e+07
4,39798.0,1085.0,998.0,733.0,1845.25,48.7,588.0,32855.0,1141.0,458.0,1118.422187,803.022535,1230.658590,0.363586,0.216669,4.018381e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7339,334986.0,20067.0,14640.0,13010.0,6834.00,40.2,460.0,246976.0,11049.0,5597.0,1028.960108,908.768412,1086.695385,0.459613,0.239198,2.818785e+08
7340,334458.0,17797.0,11533.0,9548.0,7284.00,41.1,469.0,251222.0,9838.0,5704.0,1069.247804,917.961280,1142.164298,0.462079,0.244249,2.982640e+08
7341,335062.0,19151.0,13957.0,10344.0,7088.00,41.9,474.0,252347.0,10757.0,5642.0,1070.020922,929.050634,1135.088206,0.450093,0.237804,3.009900e+08
7342,330274.0,14173.0,9787.0,7288.0,6528.00,41.5,472.0,242521.0,11039.0,5493.0,984.470527,856.126423,1041.835817,0.459325,0.226797,2.658311e+08
7343,325311.0,14984.0,10411.0,8092.0,6981.00,42.0,477.0,237826.0,11268.0,5318.0,1072.869623,917.618733,1151.874261,0.483113,0.246533,2.847394e+08